version: '2'
services:
  elasticsearch:
    image: 172.16.2.71:5000/elasticsearch:7.17.0
    container_name: elasticsearch-2
    ports: 
      - "9200:9200"
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=pureIT1999j
      - discovery.type=single-node
      - xpack.security.enabled=true
      - path.data=/usr/share/elasticsearch/data
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data      
  # logstash:
  #   image: docker.elastic.co/logstash/logstash:7.13.0
  #   container_name: logstash
  #   environment:
  #     - ELASTICSEARCH_USERNAME=elastic
  #     - ELASTICSEARCH_PASSWORD="123change..."
  #     - NODE_NAME=my-logstash
  #     - XPACK_MONITORING_ENABLED=true
  #     - PATH_CONFIG=/usr/share/logstash/my-confs
  #   volumes:
  #     - ./logstash/conf:/usr/share/logstash/my-confs
  #     - ./logstash/csv:/usr/share/logstash/csv
  #   links:
  #     - elasticsearch
  #   depends_on:
  #     - elasticsearch
  kibana:
    image: 172.16.2.71:5000/kibana:7.13.0
    container_name: kibana-2
    ports: 
      - "5601:5601"
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD="pureIT1999j"
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SERVER_NAME=my-kibana
      - XPACK_SECURITY_ENABLED=true
      - PATH_DATA=/usr/share/kibana/data
    volumes:
      - ./kibana/data:/usr/share/kibana/data
    links:
      - elasticsearch
    depends_on:
      - elasticsearch